# This will run on Travis' 'new' container-based infrastructure
sudo: false

dist: bionic

# To avoid ruby
language: generic

# Blacklist/Safelist
branches:    
  only:
    - master
#  except:
#    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: Fondamenti-II
    - GH_REPO_REF: github.com/prittt/Fondamenti-II.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build the code
#script:
#  - make

before_install:
    - sudo apt-get -y install zip 

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x scripts/generate_doc_and_deploy.sh
  - ./scripts/generate_doc_and_deploy.sh