# This will run on Travis' 'new' container-based infrastructure
sudo: false

# To avoid ruby
language: generic

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: Fondamenti-II
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/doxygen
    - GH_REPO_REF: github.com/prittt/Fondamenti-II.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build the code
#script:
#  - make

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x scripts/generate_doc_and_deploy.sh
  - ./scripts/generate_doc_and_deploy.sh