name: doc

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
        image: tsgkadot/docker-doxygen
    steps:
    - uses: actions/checkout@v2
    
    # Build the HTML documentation
    - name: Doxygen
      run: chmod +x ./scripts/generate_doc.sh && ./scripts/generate_doc.sh
      shell: bash
    
    # Deploy the HTML documentation to GitHub Pages
    - name: GH Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_REPO_TOKEN }} # ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages